[2025-03-19T22:23:52.763+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T22:23:57.165+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_taskflow_Api_v2.greet scheduled__2025-01-31T00:00:00+00:00 [queued]>
[2025-03-19T22:23:58.246+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_taskflow_Api_v2.greet scheduled__2025-01-31T00:00:00+00:00 [queued]>
[2025-03-19T22:23:58.263+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-19T22:23:58.754+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): greet> on 2025-01-31 00:00:00+00:00
[2025-03-19T22:23:59.205+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=735) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T22:23:59.229+0000] {standard_task_runner.py:72} INFO - Started process 764 to run task
[2025-03-19T22:23:59.293+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_taskflow_Api_v2', 'greet', 'scheduled__2025-01-31T00:00:00+00:00', '--job-id', '3208', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_taskflow_api.py', '--cfg-path', '/tmp/tmpuw07geoh']
[2025-03-19T22:23:59.365+0000] {standard_task_runner.py:105} INFO - Job 3208: Subtask greet
[2025-03-19T22:24:03.388+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_taskflow_Api_v2.greet scheduled__2025-01-31T00:00:00+00:00 [running]> on host 63fd4b143e0a
[2025-03-19T22:24:04.851+0000] {job.py:229} INFO - Heartbeat recovered after 13.93 seconds
[2025-03-19T22:24:10.670+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_taskflow_Api_v2' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2025-01-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-31T00:00:00+00:00'
[2025-03-19T22:24:10.936+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T22:24:11.283+0000] {logging_mixin.py:190} INFO - Hello JohnDoe, you are 19 years old.
[2025-03-19T22:24:11.329+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-19T22:24:11.763+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T22:24:11.780+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dag_with_taskflow_Api_v2, task_id=greet, run_id=scheduled__2025-01-31T00:00:00+00:00, execution_date=20250131T000000, start_date=20250319T222357, end_date=20250319T222411
[2025-03-19T22:24:12.794+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-19T22:24:14.257+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T22:24:14.465+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-19T22:24:14.522+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
