[2025-03-19T22:33:23.217+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T22:33:23.223+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_and_backfill.task_1 scheduled__2025-01-17T00:00:00+00:00 [queued]>
[2025-03-19T22:33:23.226+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_and_backfill.task_1 scheduled__2025-01-17T00:00:00+00:00 [queued]>
[2025-03-19T22:33:23.226+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-19T22:33:23.231+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task_1> on 2025-01-17 00:00:00+00:00
[2025-03-19T22:33:23.234+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3065) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T22:33:23.235+0000] {standard_task_runner.py:72} INFO - Started process 3066 to run task
[2025-03-19T22:33:23.235+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_and_backfill', 'task_1', 'scheduled__2025-01-17T00:00:00+00:00', '--job-id', '3754', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmpaniogklz']
[2025-03-19T22:33:23.238+0000] {standard_task_runner.py:105} INFO - Job 3754: Subtask task_1
[2025-03-19T22:33:23.255+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_catchup_and_backfill.task_1 scheduled__2025-01-17T00:00:00+00:00 [running]> on host 63fd4b143e0a
[2025-03-19T22:33:23.289+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_catchup_and_backfill' AIRFLOW_CTX_TASK_ID='task_1' AIRFLOW_CTX_EXECUTION_DATE='2025-01-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-17T00:00:00+00:00'
[2025-03-19T22:33:23.290+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T22:33:23.300+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-19T22:33:23.302+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo ']
[2025-03-19T22:33:23.306+0000] {subprocess.py:99} INFO - Output:
[2025-03-19T22:33:23.307+0000] {subprocess.py:106} INFO - 
[2025-03-19T22:33:23.307+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-19T22:33:23.319+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T22:33:23.320+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_and_backfill, task_id=task_1, run_id=scheduled__2025-01-17T00:00:00+00:00, execution_date=20250117T000000, start_date=20250319T223323, end_date=20250319T223323
[2025-03-19T22:33:23.375+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-19T22:33:23.392+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T22:33:23.393+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
