[2025-03-19T19:11:55.080+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T19:11:55.345+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_and_backfill.task_1 scheduled__2023-10-21T00:00:00+00:00 [queued]>
[2025-03-19T19:11:55.406+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_and_backfill.task_1 scheduled__2023-10-21T00:00:00+00:00 [queued]>
[2025-03-19T19:11:55.410+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-19T19:11:55.573+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task_1> on 2023-10-21 00:00:00+00:00
[2025-03-19T19:11:55.763+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_and_backfill', 'task_1', 'scheduled__2023-10-21T00:00:00+00:00', '--job-id', '3018', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmp6hc9gmpz']
[2025-03-19T19:11:55.796+0000] {standard_task_runner.py:105} INFO - Job 3018: Subtask task_1
[2025-03-19T19:11:55.818+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=10488) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T19:11:55.826+0000] {standard_task_runner.py:72} INFO - Started process 10506 to run task
[2025-03-19T19:11:56.681+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_catchup_and_backfill.task_1 scheduled__2023-10-21T00:00:00+00:00 [running]> on host 63fd4b143e0a
[2025-03-19T19:12:07.617+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_catchup_and_backfill' AIRFLOW_CTX_TASK_ID='task_1' AIRFLOW_CTX_EXECUTION_DATE='2023-10-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-21T00:00:00+00:00'
[2025-03-19T19:12:07.711+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T19:12:08.025+0000] {job.py:229} INFO - Heartbeat recovered after 14.07 seconds
[2025-03-19T19:12:11.474+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-19T19:12:12.234+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo ']
[2025-03-19T19:22:04.795+0000] {subprocess.py:99} INFO - Output:
[2025-03-19T19:22:04.910+0000] {subprocess.py:106} INFO - 
[2025-03-19T19:22:04.915+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-19T19:22:06.940+0000] {job.py:229} INFO - Heartbeat recovered after 599.22 seconds
[2025-03-19T19:22:10.104+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T19:22:11.128+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_and_backfill, task_id=task_1, run_id=scheduled__2023-10-21T00:00:00+00:00, execution_date=20231021T000000, start_date=20250319T191155, end_date=20250319T192211
[2025-03-19T19:22:23.852+0000] {job.py:229} INFO - Heartbeat recovered after 16.93 seconds
[2025-03-19T19:22:27.804+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-19T19:22:28.938+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-03-19T19:22:30.366+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
