[2025-03-19T22:24:40.781+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T22:24:45.976+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_taskflow_Api_v2.greet scheduled__2025-02-12T00:00:00+00:00 [queued]>
[2025-03-19T22:24:46.242+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_taskflow_Api_v2.greet scheduled__2025-02-12T00:00:00+00:00 [queued]>
[2025-03-19T22:24:46.245+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-19T22:24:47.310+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): greet> on 2025-02-12 00:00:00+00:00
[2025-03-19T22:24:47.589+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_taskflow_Api_v2', 'greet', 'scheduled__2025-02-12T00:00:00+00:00', '--job-id', '3261', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_taskflow_api.py', '--cfg-path', '/tmp/tmpjjels5dn']
[2025-03-19T22:24:47.633+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=928) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T22:24:47.656+0000] {standard_task_runner.py:72} INFO - Started process 963 to run task
[2025-03-19T22:24:47.630+0000] {standard_task_runner.py:105} INFO - Job 3261: Subtask greet
[2025-03-19T22:24:50.767+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_taskflow_Api_v2.greet scheduled__2025-02-12T00:00:00+00:00 [running]> on host 63fd4b143e0a
[2025-03-19T22:24:54.117+0000] {job.py:229} INFO - Heartbeat recovered after 14.66 seconds
[2025-03-19T22:24:54.294+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_taskflow_Api_v2' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-12T00:00:00+00:00'
[2025-03-19T22:24:54.375+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T22:24:54.434+0000] {logging_mixin.py:190} INFO - Hello JohnDoe, you are 19 years old.
[2025-03-19T22:24:54.440+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-19T22:24:54.730+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T22:24:54.746+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dag_with_taskflow_Api_v2, task_id=greet, run_id=scheduled__2025-02-12T00:00:00+00:00, execution_date=20250212T000000, start_date=20250319T222446, end_date=20250319T222454
[2025-03-19T22:24:55.362+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-19T22:24:58.767+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-03-19T22:24:59.875+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T22:25:00.204+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
